### ISSUE TITLE
Path issues regarding branches

### ISSUE THREAD

**Issue by oysteinsigholt** [hackerspace-ntnu/hackerspace-web#2]
When pushing to test the website is deployed to http://hackerspace.idi.ntnu.no/test/ and relative paths in the html code are broken. Master branch is not affected by this issue.

A suggested solution is deploying the test branch to it's own sub-domain.

**Comment by finninde** [comment]
works now, test was way behind master so the files werent included. Try pulling from master before merging in your changes.
